title: Szafshosting Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.szafshosting.de
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: true
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Szafshosting-Website
      description: Main Website
      category: nocat
    - name: E-Mail
      category: Szafshosting-Server
      description: SMTP, IMAP, POP3
    - name: Webserver
      category: Szafshosting-Server
      description: Webserver, vhosts and upload
    - name: Datenbanken
      category: Szafshosting-Server
      description: MySQL
    - name: Szeepmin
      category: Szafshosting-Server
      description: Szeepmin WebAdmin Interface
    - name: Shell-Logins
      category: Szafs-Shell-Server
      description: Logins
    - name: Infoszaf
      category: Szafs-Shell-Server
      description: Infobot
    - name: Hirte
      category: Szafs-Shell-Server
      description: Eggdrop
  dateFormat: 2006-01-02 at 15:04 UTC
  brand: "#314e8c"
  enableLastMod: true
  headerTextColor: white
  logo: https://szafshosting.de/assets/img/szaf-logo.svg
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: false
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: nocat
      untitled: true
      closed: false
    - name: Szafshosting-Server
      description: herde.szaf.org ist der aktuelle Szafshosting-Server.
      closed: false
    - name: Szafs-Shell-Server
      description: winterlamm.szaf.org ist derzeit mupfel.szaf.org
      closed: false
      untitled: false
  description: Wenn einmal wieder der Drache draufgefallen ist, erfahren Sie es hier zuerst.
  enableCustomHTML: true
  useLargeHeaderDesign: false
